<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.4.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuperStock.Application\SuperStock.Application.csproj" />
    <ProjectReference Include="..\SuperStock.Domain\SuperStock.Domain.csproj" />
    <ProjectReference Include="..\SuperStock.Infrastructure\SuperStock.Infrastructure.csproj" />
  </ItemGroup>

</Project>
